apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mcp-happyhorse
  name: mcp-happyhorse
  namespace: acedatacloud
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mcp-happyhorse
  template:
    metadata:
      labels:
        app: mcp-happyhorse
    spec:
      containers:
        - name: mcp-happyhorse
          image: ghcr.io/acedatacloud/mcp-happyhorse:${TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: MCP_SERVER_URL
              value: "https://happyhorse.mcp.acedata.cloud"
            - name: ACEDATACLOUD_OAUTH_CLIENT_ID
              value: "XjU4UFo4P5Ba6gtClGvxKXqWIoy_H0ya28h639Bh4N0"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 30m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: docker-registry