version: "3"
services:
  mcp-hcaptcha:
    platform: linux/amd64
    container_name: "mcp-hcaptcha"
    build: ./
    image: "ghcr.io/acedatacloud/mcp-hcaptcha:${BUILD_NUMBER}"
    ports:
      - "8000:8000"
