"""Canonical coverage contract for audited PlatformBackend user operations."""

from dataclasses import dataclass
from typing import Literal

Coverage = Literal["covered", "shared", "excluded", "deferred"]
Permission = Literal["public", "owner", "site_admin", "superuser", "protocol"]
Risk = Literal["read", "write", "consequential", "internal"]


@dataclass(frozen=True)
class Operation:
    """One audited backend operation and its MCP coverage state."""

    operation_id: str
    method: str
    path: str
    domain: str
    coverage: Coverage
    permission: Permission
    risk: Risk
    confirm: bool
    secret_policy: str
    test_id: str
    description: str
    tool: str | None = None
    rationale: str | None = None


def _covered(
    operation_id: str,
    method: str,
    path: str,
    domain: str,
    permission: Permission,
    risk: Risk,
    description: str,
    tool: str,
    test_id: str,
    *,
    confirm: bool = False,
    secret_policy: str = "mask",
    coverage: Coverage = "covered",
) -> Operation:
    return Operation(
        operation_id,
        method,
        path,
        domain,
        coverage,
        permission,
        risk,
        confirm,
        secret_policy,
        test_id,
        description,
        tool,
    )


def _deferred(
    operation_id: str,
    method: str,
    path: str,
    domain: str,
    risk: Risk,
    rationale: str,
    *,
    permission: Permission = "owner",
    confirm: bool = False,
    secret_policy: str = "mask",
) -> Operation:
    return Operation(
        operation_id,
        method,
        path,
        domain,
        "deferred",
        permission,
        risk,
        confirm,
        secret_policy,
        "pending",
        rationale,
        rationale=rationale,
    )


def _excluded(
    operation_id: str,
    method: str,
    path: str,
    domain: str,
    rationale: str,
) -> Operation:
    return Operation(
        operation_id,
        method,
        path,
        domain,
        "excluded",
        "protocol",
        "internal",
        False,
        "never expose",
        "not_applicable",
        rationale,
        rationale=rationale,
    )


OPERATIONS: tuple[Operation, ...] = (
    _covered(
        "subject.get",
        "GET",
        "/platform-tokens/me/",
        "Account",
        "owner",
        "read",
        "Current authenticated account profile.",
        "acedatacloud_get_user_info",
        "test_tools.py::test_get_user_info_uses_current_request_token",
    ),
    _covered(
        "services.list",
        "GET",
        "/services/",
        "Catalog",
        "public",
        "read",
        "List or search available services.",
        "acedatacloud_list_services",
        "test_tools.py::test_list_services_filters_by_search",
    ),
    _covered(
        "services.detail",
        "GET",
        "/services/",
        "Catalog",
        "public",
        "read",
        "Get one service by UUID or alias.",
        "acedatacloud_get_service",
        "test_catalog_docs.py::test_get_service_by_id_uses_id_filter",
        coverage="shared",
    ),
    _covered(
        "services.pricing",
        "GET",
        "/services/",
        "Catalog",
        "public",
        "read",
        "Get one service's display pricing.",
        "acedatacloud_get_pricing",
        "test_catalog_docs.py::test_get_pricing_returns_cost",
        coverage="shared",
    ),
    _covered(
        "apis.list",
        "GET",
        "/apis/",
        "Catalog",
        "public",
        "read",
        "List API endpoints and billing metadata.",
        "acedatacloud_list_apis",
        "test_catalog_docs.py::test_list_apis_uses_server_side_service_filter",
    ),
    _covered(
        "apis.spec",
        "GET",
        "/apis/",
        "Catalog",
        "public",
        "read",
        "Get one API's OpenAPI definition by path.",
        "acedatacloud_get_api_spec",
        "test_catalog_docs.py::test_get_api_spec_by_path",
        coverage="shared",
    ),
    _covered(
        "datasets.list",
        "GET",
        "/datasets/",
        "Catalog",
        "public",
        "read",
        "List downloadable datasets.",
        "acedatacloud_list_datasets",
        "test_catalog_docs.py::test_public_get_omits_auth_header_when_no_token",
    ),
    _covered(
        "integrations.list",
        "GET",
        "/integrations/",
        "Catalog",
        "public",
        "read",
        "List platform integrations.",
        "acedatacloud_list_integrations",
        "test_catalog_docs.py::test_public_get_omits_auth_header_when_no_token",
    ),
    _covered(
        "docs.search",
        "GET",
        "/search/",
        "Documentation",
        "public",
        "read",
        "Search public documentation.",
        "acedatacloud_search_docs",
        "test_catalog_docs.py::test_search_docs_uses_query_param",
    ),
    _covered(
        "docs.list",
        "GET",
        "/documents/",
        "Documentation",
        "public",
        "read",
        "Browse documentation pages.",
        "acedatacloud_list_docs",
        "test_catalog_docs.py::test_list_docs_passes_tag_and_private_filters",
    ),
    _covered(
        "docs.detail",
        "GET",
        "/documents/",
        "Documentation",
        "public",
        "read",
        "Fetch one documentation page by UUID.",
        "acedatacloud_get_doc",
        "test_catalog_docs.py::test_get_doc_by_id",
        coverage="shared",
    ),
    _covered(
        "models.list",
        "GET",
        "/models/",
        "Models",
        "owner",
        "read",
        "List OpenAI-compatible chat models.",
        "acedatacloud_list_models",
        "test_contract.py::test_registered_tools_match_contract",
    ),
    _covered(
        "models.catalog",
        "GET",
        "/models/catalog/",
        "Models",
        "public",
        "read",
        "List rich model metadata and pricing.",
        "acedatacloud_list_model_catalog",
        "test_catalog_docs.py::test_model_catalog_filters_modality",
    ),
    _covered(
        "models.detail",
        "GET",
        "/models/catalog/",
        "Models",
        "public",
        "read",
        "Find models by ID or name.",
        "acedatacloud_get_model",
        "test_catalog_docs.py::test_get_model_substring_match",
        coverage="shared",
    ),
    _covered(
        "applications.list",
        "GET",
        "/applications/",
        "Applications",
        "owner",
        "read",
        "List account subscriptions.",
        "acedatacloud_list_applications",
        "test_user_scope.py::test_list_applications_scopes_user_id",
    ),
    _covered(
        "applications.balance",
        "GET",
        "/applications/",
        "Applications",
        "owner",
        "read",
        "Summarize remaining Credits.",
        "acedatacloud_get_balance",
        "test_user_scope.py::test_get_balance_scopes_user_id",
        coverage="shared",
    ),
    _covered(
        "usage.api.list",
        "GET",
        "/usage/apis/",
        "Usage",
        "owner",
        "read",
        "List recent API usage records.",
        "acedatacloud_list_usage",
        "test_user_scope.py::test_registered_account_tools_are_subject_scoped",
    ),
    _covered(
        "usage.api.aggregate",
        "GET",
        "/usage/apis/aggregate/",
        "Usage",
        "owner",
        "read",
        "Aggregate API spend by API.",
        "acedatacloud_usage_summary",
        "test_user_scope.py::test_registered_account_tools_are_subject_scoped",
    ),
    _covered(
        "credentials.list",
        "GET",
        "/credentials/",
        "Credentials",
        "owner",
        "read",
        "List API credentials with secrets masked.",
        "acedatacloud_list_credentials",
        "test_user_scope.py::test_credentials_and_orders_scope_user_id_with_one_subject_lookup",
    ),
    _covered(
        "credentials.create",
        "POST",
        "/credentials/",
        "Credentials",
        "owner",
        "write",
        "Create an API credential.",
        "acedatacloud_create_credential",
        "test_tools.py::test_create_credential_confirm_gate_no_http",
        confirm=True,
        secret_policy="disclose /token once",
    ),
    _covered(
        "credentials.delete",
        "DELETE",
        "/credentials/{id}",
        "Credentials",
        "owner",
        "consequential",
        "Revoke an API credential.",
        "acedatacloud_delete_credential",
        "test_tools.py::test_delete_credential_confirm_gate",
        confirm=True,
    ),
    _covered(
        "orders.list",
        "GET",
        "/orders/",
        "Orders",
        "owner",
        "read",
        "List recharge orders.",
        "acedatacloud_list_orders",
        "test_user_scope.py::test_credentials_and_orders_scope_user_id_with_one_subject_lookup",
    ),
    _covered(
        "orders.create",
        "POST",
        "/orders/",
        "Orders",
        "owner",
        "write",
        "Create a recharge order.",
        "acedatacloud_create_order",
        "test_tools.py::test_registered_mutations_require_confirmation",
        confirm=True,
    ),
    _covered(
        "orders.pay",
        "POST",
        "/orders/{id}/pay/",
        "Orders",
        "owner",
        "consequential",
        "Create an order payment session.",
        "acedatacloud_pay_order",
        "test_tools.py::test_registered_mutations_require_confirmation",
        confirm=True,
        secret_policy="disclose /pay_url only",
    ),
    _covered(
        "platform_tokens.list",
        "GET",
        "/platform-tokens/",
        "Platform Tokens",
        "owner",
        "read",
        "List management tokens with values masked.",
        "acedatacloud_list_platform_tokens",
        "test_user_scope.py::test_registered_account_tools_are_subject_scoped",
    ),
    _covered(
        "platform_tokens.create",
        "POST",
        "/platform-tokens/",
        "Platform Tokens",
        "owner",
        "write",
        "Create a management token.",
        "acedatacloud_create_platform_token",
        "test_tools.py::test_registered_mutations_require_confirmation",
        confirm=True,
        secret_policy="disclose /token once",
    ),
    _covered(
        "platform_tokens.delete",
        "DELETE",
        "/platform-tokens/{id}/",
        "Platform Tokens",
        "owner",
        "consequential",
        "Revoke a management token.",
        "acedatacloud_delete_platform_token",
        "test_tools.py::test_registered_mutations_require_confirmation",
        confirm=True,
    ),
    _covered(
        "announcements.list",
        "GET",
        "/announcements/",
        "Announcements",
        "public",
        "read",
        "List published announcements.",
        "acedatacloud_list_announcements",
        "test_contract.py::test_registered_tools_match_contract",
    ),
    _covered(
        "announcements.create",
        "POST",
        "/announcements/admin/",
        "Admin",
        "superuser",
        "write",
        "Publish a platform announcement.",
        "acedatacloud_create_announcement",
        "test_tools.py::test_create_announcement_confirm_gate",
        confirm=True,
    ),
    _covered(
        "distribution.status",
        "GET",
        "/distribution-statuses/",
        "Distribution",
        "owner",
        "read",
        "Get referral status.",
        "acedatacloud_list_distributions",
        "test_catalog_docs.py::test_list_distributions_merges_status_and_history",
        coverage="shared",
    ),
    _covered(
        "distribution.history",
        "GET",
        "/distribution-histories/",
        "Distribution",
        "owner",
        "read",
        "List referral commission history.",
        "acedatacloud_list_distributions",
        "test_catalog_docs.py::test_list_distributions_merges_status_and_history",
        coverage="shared",
    ),
    _covered(
        "applications.create",
        "POST",
        "/applications/",
        "Applications",
        "owner",
        "write",
        "Create an application subscription.",
        "acedatacloud_create_application",
        "test_applications.py::test_create_application_confirmation_and_body",
        confirm=True,
    ),
    _covered(
        "applications.detail",
        "GET",
        "/applications/{id}",
        "Applications",
        "owner",
        "read",
        "Get one application and service details.",
        "acedatacloud_get_application",
        "test_applications.py::test_application_reads_use_exact_routes",
    ),
    _covered(
        "applications.consume_global",
        "POST",
        "/applications/{id}/update-allow-consume-global/",
        "Applications",
        "owner",
        "write",
        "Update global-balance fallback policy.",
        "acedatacloud_update_application_balance_policy",
        "test_applications.py::test_application_mutations_use_exact_routes_and_bodies",
        confirm=True,
    ),
    _covered(
        "applications.deployment.save_config",
        "POST",
        "/applications/{id}/deployment-save-config/",
        "Applications",
        "owner",
        "write",
        "Save a deployment configuration draft.",
        "acedatacloud_save_deployment_config",
        "test_applications.py::test_application_mutations_use_exact_routes_and_bodies",
        confirm=True,
    ),
    _covered(
        "applications.deployment.deploy",
        "POST",
        "/applications/{id}/deployment-deploy/",
        "Applications",
        "owner",
        "consequential",
        "Start or redeploy an application workload.",
        "acedatacloud_deploy_application",
        "test_applications.py::test_application_mutations_use_exact_routes_and_bodies",
        confirm=True,
        secret_policy="mask deployment config",
    ),
    _covered(
        "applications.deployment.status",
        "GET",
        "/applications/{id}/deployment-status/",
        "Applications",
        "owner",
        "read",
        "Get live deployment status.",
        "acedatacloud_get_deployment_status",
        "test_applications.py::test_application_reads_use_exact_routes",
    ),
    _covered(
        "applications.deployment.start",
        "POST",
        "/applications/{id}/deployment-start/",
        "Applications",
        "owner",
        "consequential",
        "Start a stopped deployment.",
        "acedatacloud_control_deployment",
        "test_applications.py::test_deployment_actions_and_teardown",
        confirm=True,
        coverage="shared",
    ),
    _covered(
        "applications.deployment.stop",
        "POST",
        "/applications/{id}/deployment-stop/",
        "Applications",
        "owner",
        "consequential",
        "Stop a deployment.",
        "acedatacloud_control_deployment",
        "test_applications.py::test_deployment_actions_and_teardown",
        confirm=True,
        coverage="shared",
    ),
    _covered(
        "applications.deployment.restart",
        "POST",
        "/applications/{id}/deployment-restart/",
        "Applications",
        "owner",
        "consequential",
        "Restart a deployment.",
        "acedatacloud_control_deployment",
        "test_applications.py::test_deployment_actions_and_teardown",
        confirm=True,
        coverage="shared",
    ),
    _covered(
        "applications.deployment.teardown",
        "POST",
        "/applications/{id}/deployment-teardown/",
        "Applications",
        "owner",
        "consequential",
        "Destroy a workload and delete its application.",
        "acedatacloud_teardown_deployment",
        "test_applications.py::test_deployment_actions_and_teardown",
        confirm=True,
    ),
    _covered(
        "applications.deployment.logs",
        "GET",
        "/applications/{id}/deployment-logs/",
        "Applications",
        "owner",
        "read",
        "Get bounded deployment logs.",
        "acedatacloud_get_deployment_logs",
        "test_applications.py::test_application_reads_use_exact_routes",
    ),
    _covered(
        "applications.deployment.events",
        "GET",
        "/applications/{id}/deployment-events/",
        "Applications",
        "owner",
        "read",
        "Get deployment scheduling events.",
        "acedatacloud_get_deployment_events",
        "test_applications.py::test_application_reads_use_exact_routes",
    ),
    _covered(
        "credentials.detail",
        "GET",
        "/credentials/{id}",
        "Credentials",
        "owner",
        "read",
        "Get one credential with secrets masked.",
        "acedatacloud_get_credential",
        "test_credentials.py::test_credential_detail_masks_secret",
    ),
    _covered(
        "credentials.update",
        "PATCH",
        "/credentials/{id}",
        "Credentials",
        "owner",
        "write",
        "Update credential limits and API scope.",
        "acedatacloud_update_credential",
        "test_credentials.py::test_update_credential_route_and_body",
        confirm=True,
    ),
    _covered(
        "credentials.rotate",
        "POST",
        "/credentials/{id}/rotate/",
        "Credentials",
        "owner",
        "consequential",
        "Rotate and disclose a credential secret once.",
        "acedatacloud_rotate_credential",
        "test_credentials.py::test_rotate_discloses_only_rotated_secret",
        confirm=True,
        secret_policy="disclose /token or /password once",
    ),
    _covered(
        "orders.detail",
        "GET",
        "/orders/{id}",
        "Orders",
        "owner",
        "read",
        "Get one order.",
        "acedatacloud_get_order",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "orders.summary",
        "GET",
        "/orders/summary/",
        "Orders",
        "owner",
        "read",
        "Summarize caller orders.",
        "acedatacloud_get_order_summary",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "orders.export",
        "GET",
        "/orders/export/",
        "Orders",
        "owner",
        "read",
        "Export bounded order CSV.",
        "acedatacloud_export_orders",
        "test_billing_tools.py::test_bounded_exports",
    ),
    _covered(
        "orders.refresh",
        "POST",
        "/orders/{id}/refresh/",
        "Orders",
        "owner",
        "consequential",
        "Refresh payment state.",
        "acedatacloud_refresh_order",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
    ),
    _covered(
        "orders.apple_verify",
        "POST",
        "/orders/{id}/apple-verify/",
        "Orders",
        "owner",
        "consequential",
        "Verify and fulfill Apple IAP.",
        "acedatacloud_verify_apple_order",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
    ),
    _covered(
        "orders.invoice",
        "GET",
        "/orders/{id}/invoice/",
        "Invoices",
        "owner",
        "read",
        "Get an order's active invoice.",
        "acedatacloud_get_order_invoice",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "billing_profiles.list",
        "GET",
        "/billing-profiles/",
        "Invoices",
        "owner",
        "read",
        "List billing profiles.",
        "acedatacloud_list_billing_profiles",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "invoices.preview",
        "POST",
        "/invoices/preview/",
        "Invoices",
        "owner",
        "read",
        "Preview invoice amount.",
        "acedatacloud_preview_invoice",
        "test_billing_tools.py::test_invoice_preview_route",
    ),
    _covered(
        "invoices.list",
        "GET",
        "/invoices/",
        "Invoices",
        "owner",
        "read",
        "List invoices.",
        "acedatacloud_list_invoices",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "invoices.apply",
        "POST",
        "/invoices/",
        "Invoices",
        "owner",
        "write",
        "Apply for an invoice.",
        "acedatacloud_apply_invoice",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
    ),
    _covered(
        "invoices.detail",
        "GET",
        "/invoices/{id}/",
        "Invoices",
        "owner",
        "read",
        "Get one invoice.",
        "acedatacloud_get_invoice",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "invoices.cancel",
        "POST",
        "/invoices/{id}/cancel/",
        "Invoices",
        "owner",
        "consequential",
        "Cancel an invoice.",
        "acedatacloud_cancel_invoice",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
    ),
    _covered(
        "invoices.download",
        "GET",
        "/invoices/{id}/download/",
        "Invoices",
        "owner",
        "read",
        "Get a signed invoice URL.",
        "acedatacloud_get_invoice_download",
        "test_billing_tools.py::test_invoice_download_json_url",
        secret_policy="disclose /url only",
    ),
    _covered(
        "auto_recharge.list",
        "GET",
        "/auto-recharge-configs/",
        "Auto Recharge",
        "owner",
        "read",
        "List auto-recharge configs.",
        "acedatacloud_list_auto_recharges",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "auto_recharge.create",
        "POST",
        "/auto-recharge-configs/",
        "Auto Recharge",
        "owner",
        "write",
        "Create auto recharge.",
        "acedatacloud_create_auto_recharge",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
    ),
    _covered(
        "auto_recharge.detail",
        "GET",
        "/auto-recharge-configs/{id}",
        "Auto Recharge",
        "owner",
        "read",
        "Get auto recharge.",
        "acedatacloud_get_auto_recharge",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "auto_recharge.update",
        "PATCH",
        "/auto-recharge-configs/{id}",
        "Auto Recharge",
        "owner",
        "write",
        "Update auto recharge.",
        "acedatacloud_update_auto_recharge",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
    ),
    _covered(
        "auto_recharge.delete",
        "DELETE",
        "/auto-recharge-configs/{id}",
        "Auto Recharge",
        "owner",
        "consequential",
        "Delete auto recharge.",
        "acedatacloud_delete_auto_recharge",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
    ),
    _covered(
        "auto_recharge.quote",
        "POST",
        "/auto-recharge-configs/quote/",
        "Auto Recharge",
        "owner",
        "read",
        "Quote auto recharge.",
        "acedatacloud_quote_auto_recharge",
        "test_billing_tools.py::test_auto_recharge_quote_route",
    ),
    _covered(
        "auto_recharge.setup",
        "POST",
        "/auto-recharge-configs/{id}/setup/",
        "Auto Recharge",
        "owner",
        "consequential",
        "Create card setup state.",
        "acedatacloud_setup_auto_recharge",
        "test_billing_tools.py::test_setup_exact_secret_disclosure",
        confirm=True,
        secret_policy="disclose /client_secret and /id once",
    ),
    _covered(
        "auto_recharge.confirm",
        "POST",
        "/auto-recharge-configs/{id}/confirm-setup/",
        "Auto Recharge",
        "owner",
        "consequential",
        "Confirm saved card setup.",
        "acedatacloud_confirm_auto_recharge_setup",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
    ),
    _covered(
        "auto_recharge.disable",
        "POST",
        "/auto-recharge-configs/{id}/disable/",
        "Auto Recharge",
        "owner",
        "consequential",
        "Disable auto recharge.",
        "acedatacloud_disable_auto_recharge",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
    ),
    _covered(
        "usage.api.detail",
        "GET",
        "/usage/apis/{id}",
        "Usage",
        "owner",
        "read",
        "Get API usage detail.",
        "acedatacloud_get_usage",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "usage.api.status_codes",
        "GET",
        "/usage/apis/status-codes/",
        "Usage",
        "owner",
        "read",
        "List usage status codes.",
        "acedatacloud_list_usage_status_codes",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "usage.api.export",
        "GET",
        "/usage/apis/export/",
        "Usage",
        "owner",
        "read",
        "Export bounded usage CSV.",
        "acedatacloud_export_usage",
        "test_billing_tools.py::test_bounded_exports",
    ),
    _covered(
        "usage.proxy.list",
        "GET",
        "/usage/proxies/",
        "Usage",
        "owner",
        "read",
        "List proxy usage.",
        "acedatacloud_list_proxy_usage",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _covered(
        "usage.proxy.detail",
        "GET",
        "/usage/proxies/{id}",
        "Usage",
        "owner",
        "read",
        "Get proxy usage detail.",
        "acedatacloud_get_proxy_usage",
        "test_billing_tools.py::test_billing_read_routes",
    ),
    _deferred(
        "distribution.lifecycle",
        "MULTI",
        "/distribution-*",
        "Distribution",
        "write",
        "Initialize, ranks, trend and levels are planned for PR 4.",
        confirm=True,
    ),
    _deferred(
        "coin.lifecycle",
        "MULTI",
        "/coin-*",
        "Coin",
        "consequential",
        "Wallet summary, challenge and confirmation are planned for PR 4.",
        confirm=True,
        secret_policy="never echo signatures",
    ),
    _deferred(
        "access_requests.lifecycle",
        "MULTI",
        "/access-requests/*",
        "Access Requests",
        "write",
        "Typed owner-scoped lifecycle is planned for PR 4.",
        confirm=True,
    ),
    _deferred(
        "surveys.lifecycle",
        "MULTI",
        "/surveys/*",
        "Surveys",
        "write",
        "Templates, submission and caller responses are planned for PR 4.",
        confirm=True,
    ),
    _deferred(
        "translation.lifecycle",
        "MULTI",
        "/translation-*",
        "Translation",
        "write",
        "Capabilities, enable and disable are planned for PR 4.",
        confirm=True,
    ),
    _deferred(
        "email_preferences.lifecycle",
        "MULTI",
        "/email-preferences/*",
        "Preferences",
        "write",
        "Topic reads and updates are planned for PR 4.",
        confirm=True,
    ),
    _deferred(
        "content_reports.create",
        "POST",
        "/content-reports/",
        "Reports",
        "write",
        "Planned for PR 4.",
        confirm=True,
    ),
    _deferred(
        "x402.lifecycle",
        "MULTI",
        "/x402-authorizations/*",
        "X402",
        "consequential",
        "Typed setup, signing confirmation and revoke lifecycle are planned for PR 4.",
        confirm=True,
        secret_policy="redact signatures and transactions",
    ),
    _deferred(
        "sites.lifecycle",
        "MULTI",
        "/sites/*",
        "Sites",
        "consequential",
        "Site, domain, banner and override tools are planned for PR 5.",
        permission="site_admin",
        confirm=True,
    ),
    _excluded(
        "applications.appliance_proxy",
        "ANY",
        "/applications/{id}/appliance-request",
        "Applications",
        "Generic appliance reverse proxy would bypass typed MCP safety boundaries.",
    ),
    _excluded(
        "payments.provider",
        "ANY",
        "/payment/*",
        "Payments",
        "Provider-internal payment APIs are not account control-plane operations.",
    ),
    _excluded(
        "callbacks.oauth",
        "ANY",
        "*/oauth/callback",
        "Protocols",
        "OAuth callbacks are interactive protocol endpoints, not callable tools.",
    ),
    _excluded(
        "callbacks.webhooks",
        "ANY",
        "*/webhook/*",
        "Protocols",
        "Inbound provider callbacks must never be exposed as caller-driven tools.",
    ),
    _excluded(
        "auth.interactive",
        "ANY",
        "/auth/login|register|codes|reset",
        "Protocols",
        "Interactive login, registration, verification codes and password reset remain client flows.",
    ),
    _excluded(
        "webauthn.protocol",
        "ANY",
        "/passkeys/*/challenge|verify",
        "Protocols",
        "WebAuthn challenge and verification require browser-native origin-bound credentials.",
    ),
    _excluded(
        "uploads.public_token",
        "ANY",
        "/uploads/public/*",
        "Protocols",
        "Public tokenized upload callbacks are protocol surfaces, not management tools.",
    ),
)
