"""Canonical coverage contract for audited PlatformBackend user operations."""

from dataclasses import dataclass
from typing import Literal

Coverage = Literal["covered", "shared", "excluded", "deferred"]
Authentication = Literal["public", "authenticated"]
Risk = Literal["read", "write", "consequential", "internal"]


@dataclass(frozen=True)
class Operation:
    """One audited backend operation and its MCP coverage state."""

    operation_id: str
    method: str
    path: str
    domain: str
    coverage: Coverage
    authentication: Authentication
    required_permissions: tuple[str, ...]
    risk: Risk
    confirm: bool
    secret_policy: str
    test_id: str
    description: str
    tool: str | None = None
    rationale: str | None = None


def _covered(
    operation_id: str,
    method: str,
    path: str,
    domain: str,
    authentication: Authentication,
    risk: Risk,
    description: str,
    tool: str,
    test_id: str,
    *,
    confirm: bool = False,
    required_permissions: tuple[str, ...] = (),
    secret_policy: str = "mask",
    coverage: Coverage = "covered",
) -> Operation:
    return Operation(
        operation_id,
        method,
        path,
        domain,
        coverage,
        authentication,
        required_permissions,
        risk,
        confirm,
        secret_policy,
        test_id,
        description,
        tool,
    )


def _excluded(
    operation_id: str,
    method: str,
    path: str,
    domain: str,
    rationale: str,
) -> Operation:
    return Operation(
        operation_id,
        method,
        path,
        domain,
        "excluded",
        "authenticated",
        (),
        "internal",
        False,
        "never expose",
        "not_applicable",
        rationale,
        rationale=rationale,
    )


OPERATIONS: tuple[Operation, ...] = (
    _covered(
        "blog.public_list",
        "GET",
        "/blogs/",
        "Blog",
        "public",
        "read",
        "List published blog posts.",
        "acedatacloud_list_blog_posts",
        "test_blog_tools.py::test_public_blog_reads_do_not_forward_credentials",
        confirm=False,
        coverage="covered",
        required_permissions=(),
    ),
    _covered(
        "blog.public_detail",
        "GET",
        "/blogs/{slug}/",
        "Blog",
        "public",
        "read",
        "Read a localized published blog post.",
        "acedatacloud_get_blog_post",
        "test_blog_tools.py::test_public_blog_reads_do_not_forward_credentials",
        confirm=False,
        coverage="covered",
        required_permissions=(),
    ),
    _covered(
        "blog.admin_list",
        "GET",
        "/blogs/admin/",
        "Blog",
        "authenticated",
        "read",
        "List blog drafts and published editorial records.",
        "acedatacloud_list_blog_drafts",
        "test_blog_tools.py::test_editorial_reads_and_filters",
        confirm=False,
        coverage="covered",
        required_permissions=("blog:read",),
    ),
    _covered(
        "blog.admin_detail",
        "GET",
        "/blogs/admin/{id}/",
        "Blog",
        "authenticated",
        "read",
        "Read full editable blog source.",
        "acedatacloud_get_blog_draft",
        "test_blog_tools.py::test_editorial_reads_and_filters",
        confirm=False,
        coverage="covered",
        required_permissions=("blog:read",),
    ),
    _covered(
        "blog.comments_list",
        "GET",
        "/blogs/admin/{id}/comments/",
        "Blog",
        "authenticated",
        "read",
        "Read private review threads and replies.",
        "acedatacloud_list_blog_comments",
        "test_blog_tools.py::test_review_comments",
        required_permissions=("blog:read",),
    ),
    _covered(
        "blog.comments_create",
        "POST",
        "/blogs/admin/{id}/comments/",
        "Blog",
        "authenticated",
        "write",
        "Add a review comment; requires blog:read and either blog:write or blog:publish.",
        "acedatacloud_add_blog_comment",
        "test_blog_tools.py::test_review_comments",
        confirm=True,
        required_permissions=("blog:read",),
    ),
    _covered(
        "blog.comments_reply",
        "POST",
        "/blogs/admin/{id}/comments/{comment_id}/replies/",
        "Blog",
        "authenticated",
        "write",
        "Reply to a review comment; requires blog:read and either blog:write or blog:publish.",
        "acedatacloud_reply_blog_comment",
        "test_blog_tools.py::test_review_comments",
        confirm=True,
        required_permissions=("blog:read",),
    ),
    _covered(
        "blog.comments_resolve",
        "PATCH",
        "/blogs/admin/{id}/comments/{comment_id}/",
        "Blog",
        "authenticated",
        "write",
        "Resolve or reopen a review thread; requires blog:read and either blog:write or blog:publish.",
        "acedatacloud_resolve_blog_comment",
        "test_blog_tools.py::test_review_comments",
        confirm=True,
        required_permissions=("blog:read",),
    ),
    _covered(
        "blog.create",
        "POST",
        "/blogs/admin/",
        "Blog",
        "authenticated",
        "write",
        "Save an unpublished blog draft.",
        "acedatacloud_create_blog_draft",
        "test_blog_tools.py::test_create_draft_and_preserve_markdown",
        confirm=True,
        coverage="covered",
        required_permissions=("blog:write",),
    ),
    _covered(
        "blog.update",
        "PATCH",
        "/blogs/admin/{id}/",
        "Blog",
        "authenticated",
        "write",
        "Edit draft source; unpublish before changing public content.",
        "acedatacloud_update_blog_post",
        "test_blog_tools.py::test_update_only_sends_supplied_fields",
        confirm=True,
        coverage="covered",
        required_permissions=("blog:write",),
    ),
    _covered(
        "blog.submit",
        "POST",
        "/blogs/admin/{id}/submit/",
        "Blog",
        "authenticated",
        "write",
        "Submit a draft or rejected post for review.",
        "acedatacloud_submit_blog_post",
        "test_blog_tools.py::test_review_submission_and_rejection",
        confirm=True,
        coverage="covered",
        required_permissions=("blog:write",),
    ),
    _covered(
        "blog.withdraw_submission",
        "DELETE",
        "/blogs/admin/{id}/submit/",
        "Blog",
        "authenticated",
        "write",
        "Withdraw a pending review request.",
        "acedatacloud_withdraw_blog_submission",
        "test_blog_tools.py::test_review_submission_and_rejection",
        confirm=True,
        coverage="covered",
        required_permissions=("blog:write",),
    ),
    _covered(
        "blog.approve",
        "POST",
        "/blogs/admin/{id}/approval/",
        "Blog",
        "authenticated",
        "consequential",
        "Approve a submitted version as a different account from its creator.",
        "acedatacloud_approve_blog_post",
        "test_blog_tools.py::test_approve_and_withdraw_blog_review",
        confirm=True,
        coverage="covered",
        required_permissions=("blog:read", "blog:publish"),
    ),
    _covered(
        "blog.reject",
        "POST",
        "/blogs/admin/{id}/reject/",
        "Blog",
        "authenticated",
        "consequential",
        "Reject a submitted version using a summary or an existing open review comment.",
        "acedatacloud_reject_blog_post",
        "test_blog_tools.py::test_review_submission_and_rejection",
        confirm=True,
        coverage="covered",
        required_permissions=("blog:read", "blog:publish"),
    ),
    _covered(
        "blog.withdraw_approval",
        "DELETE",
        "/blogs/admin/{id}/approval/",
        "Blog",
        "authenticated",
        "consequential",
        "Withdraw approval before publication.",
        "acedatacloud_withdraw_blog_approval",
        "test_blog_tools.py::test_approve_and_withdraw_blog_review",
        confirm=True,
        coverage="covered",
        required_permissions=("blog:read", "blog:publish"),
    ),
    _covered(
        "blog.publish",
        "PATCH",
        "/blogs/admin/{id}/",
        "Blog",
        "authenticated",
        "consequential",
        "Publish an approved draft now or schedule its public visibility.",
        "acedatacloud_publish_blog_post",
        "test_blog_tools.py::test_publication_actions_use_backend_permissions",
        confirm=True,
        coverage="shared",
        required_permissions=("blog:write", "blog:publish"),
    ),
    _covered(
        "blog.unpublish",
        "PATCH",
        "/blogs/admin/{id}/",
        "Blog",
        "authenticated",
        "consequential",
        "Return a public blog post to draft.",
        "acedatacloud_unpublish_blog_post",
        "test_blog_tools.py::test_publication_actions_use_backend_permissions",
        confirm=True,
        coverage="shared",
        required_permissions=("blog:write", "blog:publish"),
    ),
    _covered(
        "blog.delete",
        "DELETE",
        "/blogs/admin/{id}/",
        "Blog",
        "authenticated",
        "consequential",
        "Delete a blog and its translations.",
        "acedatacloud_delete_blog_post",
        "test_blog_tools.py::test_delete_blog_post",
        confirm=True,
        coverage="covered",
        required_permissions=("blog:write",),
    ),
    _covered(
        "subject.get",
        "GET",
        "/platform-tokens/me/",
        "Account",
        "authenticated",
        "read",
        "Current authenticated account profile.",
        "acedatacloud_get_user_info",
        "test_tools.py::test_get_user_info_uses_current_request_token",
        required_permissions=(),
    ),
    _covered(
        "services.list",
        "GET",
        "/services/",
        "Catalog",
        "public",
        "read",
        "List or search available services.",
        "acedatacloud_list_services",
        "test_tools.py::test_list_services_filters_by_search",
        required_permissions=(),
    ),
    _covered(
        "services.detail",
        "GET",
        "/services/",
        "Catalog",
        "public",
        "read",
        "Get one service by UUID or alias.",
        "acedatacloud_get_service",
        "test_catalog_docs.py::test_get_service_by_id_uses_id_filter",
        coverage="shared",
        required_permissions=(),
    ),
    _covered(
        "services.pricing",
        "GET",
        "/services/",
        "Catalog",
        "public",
        "read",
        "Get one service's display pricing.",
        "acedatacloud_get_pricing",
        "test_catalog_docs.py::test_get_pricing_returns_cost",
        coverage="shared",
        required_permissions=(),
    ),
    _covered(
        "services.public_usage_packages",
        "GET",
        "/services/{id}/",
        "Catalog",
        "public",
        "read",
        "Get a service's public Usage package amount and price for Credit-to-USD conversion.",
        "acedatacloud_get_public_usage_packages",
        "test_catalog_docs.py::test_get_public_usage_packages_returns_positive_raw_ladder",
        coverage="shared",
        required_permissions=(),
    ),
    _covered(
        "apis.list",
        "GET",
        "/apis/",
        "Catalog",
        "public",
        "read",
        "List API endpoints and billing metadata.",
        "acedatacloud_list_apis",
        "test_catalog_docs.py::test_list_apis_uses_server_side_service_filter",
        required_permissions=(),
    ),
    _covered(
        "apis.spec",
        "GET",
        "/apis/",
        "Catalog",
        "public",
        "read",
        "Get one API's OpenAPI definition by path.",
        "acedatacloud_get_api_spec",
        "test_catalog_docs.py::test_get_api_spec_by_path",
        coverage="shared",
        required_permissions=(),
    ),
    _covered(
        "datasets.list",
        "GET",
        "/datasets/",
        "Catalog",
        "public",
        "read",
        "List downloadable datasets.",
        "acedatacloud_list_datasets",
        "test_catalog_docs.py::test_public_get_omits_auth_header_when_no_token",
        required_permissions=(),
    ),
    _covered(
        "integrations.list",
        "GET",
        "/integrations/",
        "Catalog",
        "public",
        "read",
        "List platform integrations.",
        "acedatacloud_list_integrations",
        "test_catalog_docs.py::test_public_get_omits_auth_header_when_no_token",
        required_permissions=(),
    ),
    _covered(
        "docs.search",
        "GET",
        "/search/",
        "Documentation",
        "public",
        "read",
        "Search public documentation.",
        "acedatacloud_search_docs",
        "test_catalog_docs.py::test_search_docs_uses_query_param",
        required_permissions=(),
    ),
    _covered(
        "docs.list",
        "GET",
        "/documents/",
        "Documentation",
        "public",
        "read",
        "Browse documentation pages.",
        "acedatacloud_list_docs",
        "test_catalog_docs.py::test_list_docs_passes_tag_and_private_filters",
        required_permissions=(),
    ),
    _covered(
        "docs.detail",
        "GET",
        "/documents/",
        "Documentation",
        "public",
        "read",
        "Fetch one documentation page by UUID.",
        "acedatacloud_get_doc",
        "test_catalog_docs.py::test_get_doc_by_id",
        coverage="shared",
        required_permissions=(),
    ),
    _covered(
        "models.list",
        "GET",
        "/models/",
        "Models",
        "authenticated",
        "read",
        "List OpenAI-compatible chat models.",
        "acedatacloud_list_models",
        "test_contract.py::test_registered_tools_match_contract",
        required_permissions=(),
    ),
    _covered(
        "models.catalog",
        "GET",
        "/models/catalog/",
        "Models",
        "public",
        "read",
        "List rich model metadata and pricing.",
        "acedatacloud_list_model_catalog",
        "test_catalog_docs.py::test_model_catalog_filters_modality",
        required_permissions=(),
    ),
    _covered(
        "models.detail",
        "GET",
        "/models/catalog/",
        "Models",
        "public",
        "read",
        "Find models by ID or name.",
        "acedatacloud_get_model",
        "test_catalog_docs.py::test_get_model_substring_match",
        coverage="shared",
        required_permissions=(),
    ),
    _covered(
        "applications.list",
        "GET",
        "/applications/",
        "Applications",
        "authenticated",
        "read",
        "List account subscriptions.",
        "acedatacloud_list_applications",
        "test_user_scope.py::test_list_applications_scopes_user_id",
        required_permissions=("applications:read",),
    ),
    _covered(
        "applications.balance",
        "GET",
        "/applications/",
        "Applications",
        "authenticated",
        "read",
        "Summarize remaining Credits.",
        "acedatacloud_get_balance",
        "test_user_scope.py::test_get_balance_scopes_user_id",
        coverage="shared",
        required_permissions=("applications:read",),
    ),
    _covered(
        "usage.api.list",
        "GET",
        "/usage/apis/",
        "Usage",
        "authenticated",
        "read",
        "List recent API usage records.",
        "acedatacloud_list_usage",
        "test_user_scope.py::test_registered_account_tools_are_subject_scoped",
        required_permissions=("usage:read",),
    ),
    _covered(
        "usage.api.aggregate",
        "GET",
        "/usage/apis/aggregate/",
        "Usage",
        "authenticated",
        "read",
        "Aggregate API spend by API.",
        "acedatacloud_usage_summary",
        "test_user_scope.py::test_registered_account_tools_are_subject_scoped",
        required_permissions=("usage:read",),
    ),
    _covered(
        "credentials.list",
        "GET",
        "/credentials/",
        "Credentials",
        "authenticated",
        "read",
        "List API credentials with secrets masked.",
        "acedatacloud_list_credentials",
        "test_user_scope.py::test_credentials_and_orders_scope_user_id_with_one_subject_lookup",
        required_permissions=("credentials:read",),
    ),
    _covered(
        "credentials.create",
        "POST",
        "/credentials/",
        "Credentials",
        "authenticated",
        "write",
        "Create an API credential.",
        "acedatacloud_create_credential",
        "test_tools.py::test_create_credential_confirm_gate_no_http",
        confirm=True,
        secret_policy="disclose /token once",
        required_permissions=("credentials:write",),
    ),
    _covered(
        "credentials.delete",
        "DELETE",
        "/credentials/{id}",
        "Credentials",
        "authenticated",
        "consequential",
        "Revoke an API credential.",
        "acedatacloud_delete_credential",
        "test_tools.py::test_delete_credential_confirm_gate",
        confirm=True,
        required_permissions=("credentials:write",),
    ),
    _covered(
        "orders.list",
        "GET",
        "/orders/",
        "Orders",
        "authenticated",
        "read",
        "List recharge orders.",
        "acedatacloud_list_orders",
        "test_user_scope.py::test_credentials_and_orders_scope_user_id_with_one_subject_lookup",
        required_permissions=("orders:read",),
    ),
    _covered(
        "orders.create",
        "POST",
        "/orders/",
        "Orders",
        "authenticated",
        "write",
        "Create a recharge order.",
        "acedatacloud_create_order",
        "test_tools.py::test_registered_mutations_require_confirmation",
        confirm=True,
        required_permissions=("orders:write",),
    ),
    _covered(
        "orders.pay",
        "POST",
        "/orders/{id}/pay/",
        "Orders",
        "authenticated",
        "consequential",
        "Create an order payment session.",
        "acedatacloud_pay_order",
        "test_tools.py::test_registered_mutations_require_confirmation",
        confirm=True,
        secret_policy="disclose /pay_url only",
        required_permissions=(),
    ),
    _covered(
        "platform_tokens.list",
        "GET",
        "/platform-tokens/",
        "Platform Tokens",
        "authenticated",
        "read",
        "List management tokens with values masked.",
        "acedatacloud_list_platform_tokens",
        "test_user_scope.py::test_registered_account_tools_are_subject_scoped",
        required_permissions=(),
    ),
    _covered(
        "platform_tokens.create",
        "POST",
        "/platform-tokens/",
        "Platform Tokens",
        "authenticated",
        "write",
        "Create a management token.",
        "acedatacloud_create_platform_token",
        "test_tools.py::test_registered_mutations_require_confirmation",
        confirm=True,
        secret_policy="disclose /token once",
        required_permissions=(),
    ),
    _covered(
        "platform_tokens.delete",
        "DELETE",
        "/platform-tokens/{id}/",
        "Platform Tokens",
        "authenticated",
        "consequential",
        "Revoke a management token.",
        "acedatacloud_delete_platform_token",
        "test_tools.py::test_registered_mutations_require_confirmation",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "announcements.list",
        "GET",
        "/announcements/",
        "Announcements",
        "public",
        "read",
        "List published announcements.",
        "acedatacloud_list_announcements",
        "test_contract.py::test_registered_tools_match_contract",
        required_permissions=(),
    ),
    _covered(
        "announcements.create",
        "POST",
        "/announcements/admin/",
        "Admin",
        "authenticated",
        "write",
        "Publish a platform announcement.",
        "acedatacloud_create_announcement",
        "test_tools.py::test_create_announcement_confirm_gate",
        confirm=True,
        required_permissions=("announcements:write",),
    ),
    _covered(
        "distribution.status",
        "GET",
        "/distribution-statuses/",
        "Distribution",
        "authenticated",
        "read",
        "Get referral status.",
        "acedatacloud_list_distributions",
        "test_catalog_docs.py::test_list_distributions_merges_status_and_history",
        coverage="shared",
        required_permissions=(),
    ),
    _covered(
        "distribution.history",
        "GET",
        "/distribution-histories/",
        "Distribution",
        "authenticated",
        "read",
        "List referral commission history.",
        "acedatacloud_list_distributions",
        "test_catalog_docs.py::test_list_distributions_merges_status_and_history",
        coverage="shared",
        required_permissions=(),
    ),
    _covered(
        "applications.create",
        "POST",
        "/applications/",
        "Applications",
        "authenticated",
        "write",
        "Create an application subscription.",
        "acedatacloud_create_application",
        "test_applications.py::test_create_application_confirmation_and_body",
        confirm=True,
        required_permissions=("applications:write",),
    ),
    _covered(
        "applications.detail",
        "GET",
        "/applications/{id}",
        "Applications",
        "authenticated",
        "read",
        "Get one application and service details.",
        "acedatacloud_get_application",
        "test_applications.py::test_application_reads_use_exact_routes",
        required_permissions=("applications:read",),
    ),
    _covered(
        "applications.consume_global",
        "POST",
        "/applications/{id}/update-allow-consume-global/",
        "Applications",
        "authenticated",
        "write",
        "Update global-balance fallback policy.",
        "acedatacloud_update_application_balance_policy",
        "test_applications.py::test_application_mutations_use_exact_routes_and_bodies",
        confirm=True,
        required_permissions=("applications:write",),
    ),
    _covered(
        "applications.deployment.save_config",
        "POST",
        "/applications/{id}/deployment-save-config/",
        "Applications",
        "authenticated",
        "write",
        "Save a deployment configuration draft.",
        "acedatacloud_save_deployment_config",
        "test_applications.py::test_application_mutations_use_exact_routes_and_bodies",
        confirm=True,
        required_permissions=("applications:write",),
    ),
    _covered(
        "applications.deployment.deploy",
        "POST",
        "/applications/{id}/deployment-deploy/",
        "Applications",
        "authenticated",
        "consequential",
        "Start or redeploy an application workload.",
        "acedatacloud_deploy_application",
        "test_applications.py::test_application_mutations_use_exact_routes_and_bodies",
        confirm=True,
        secret_policy="mask deployment config",
        required_permissions=("applications:write",),
    ),
    _covered(
        "applications.deployment.status",
        "GET",
        "/applications/{id}/deployment-status/",
        "Applications",
        "authenticated",
        "read",
        "Get live deployment status.",
        "acedatacloud_get_deployment_status",
        "test_applications.py::test_application_reads_use_exact_routes",
        required_permissions=("applications:read",),
    ),
    _covered(
        "applications.deployment.start",
        "POST",
        "/applications/{id}/deployment-start/",
        "Applications",
        "authenticated",
        "consequential",
        "Start a stopped deployment.",
        "acedatacloud_control_deployment",
        "test_applications.py::test_deployment_actions_and_teardown",
        confirm=True,
        coverage="shared",
        required_permissions=("applications:write",),
    ),
    _covered(
        "applications.deployment.stop",
        "POST",
        "/applications/{id}/deployment-stop/",
        "Applications",
        "authenticated",
        "consequential",
        "Stop a deployment.",
        "acedatacloud_control_deployment",
        "test_applications.py::test_deployment_actions_and_teardown",
        confirm=True,
        coverage="shared",
        required_permissions=("applications:write",),
    ),
    _covered(
        "applications.deployment.restart",
        "POST",
        "/applications/{id}/deployment-restart/",
        "Applications",
        "authenticated",
        "consequential",
        "Restart a deployment.",
        "acedatacloud_control_deployment",
        "test_applications.py::test_deployment_actions_and_teardown",
        confirm=True,
        coverage="shared",
        required_permissions=("applications:write",),
    ),
    _covered(
        "applications.deployment.teardown",
        "POST",
        "/applications/{id}/deployment-teardown/",
        "Applications",
        "authenticated",
        "consequential",
        "Destroy a workload and delete its application.",
        "acedatacloud_teardown_deployment",
        "test_applications.py::test_deployment_actions_and_teardown",
        confirm=True,
        required_permissions=("applications:write",),
    ),
    _covered(
        "applications.deployment.logs",
        "GET",
        "/applications/{id}/deployment-logs/",
        "Applications",
        "authenticated",
        "read",
        "Get bounded deployment logs.",
        "acedatacloud_get_deployment_logs",
        "test_applications.py::test_application_reads_use_exact_routes",
        required_permissions=("applications:read",),
    ),
    _covered(
        "applications.deployment.events",
        "GET",
        "/applications/{id}/deployment-events/",
        "Applications",
        "authenticated",
        "read",
        "Get deployment scheduling events.",
        "acedatacloud_get_deployment_events",
        "test_applications.py::test_application_reads_use_exact_routes",
        required_permissions=("applications:read",),
    ),
    _covered(
        "credentials.detail",
        "GET",
        "/credentials/{id}",
        "Credentials",
        "authenticated",
        "read",
        "Get one credential with secrets masked.",
        "acedatacloud_get_credential",
        "test_credentials.py::test_credential_detail_masks_secret",
        required_permissions=("credentials:read",),
    ),
    _covered(
        "credentials.update",
        "PATCH",
        "/credentials/{id}",
        "Credentials",
        "authenticated",
        "write",
        "Update credential limits and API scope.",
        "acedatacloud_update_credential",
        "test_credentials.py::test_update_credential_route_and_body",
        confirm=True,
        required_permissions=("credentials:write",),
    ),
    _covered(
        "credentials.rotate",
        "POST",
        "/credentials/{id}/rotate/",
        "Credentials",
        "authenticated",
        "consequential",
        "Rotate and disclose a credential secret once.",
        "acedatacloud_rotate_credential",
        "test_credentials.py::test_rotate_discloses_only_rotated_secret",
        confirm=True,
        secret_policy="disclose /token or /password once",
        required_permissions=(),
    ),
    _covered(
        "orders.detail",
        "GET",
        "/orders/{id}",
        "Orders",
        "authenticated",
        "read",
        "Get one order.",
        "acedatacloud_get_order",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=("orders:read",),
    ),
    _covered(
        "orders.summary",
        "GET",
        "/orders/summary/",
        "Orders",
        "authenticated",
        "read",
        "Summarize caller orders.",
        "acedatacloud_get_order_summary",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=("orders:read",),
    ),
    _covered(
        "orders.export",
        "GET",
        "/orders/export/",
        "Orders",
        "authenticated",
        "read",
        "Export bounded order CSV.",
        "acedatacloud_export_orders",
        "test_billing_tools.py::test_bounded_exports",
        required_permissions=("orders:read",),
    ),
    _covered(
        "orders.refresh",
        "POST",
        "/orders/{id}/refresh/",
        "Orders",
        "authenticated",
        "consequential",
        "Refresh payment state.",
        "acedatacloud_refresh_order",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
        required_permissions=("orders:write",),
    ),
    _covered(
        "orders.apple_verify",
        "POST",
        "/orders/{id}/apple-verify/",
        "Orders",
        "authenticated",
        "consequential",
        "Verify and fulfill Apple IAP.",
        "acedatacloud_verify_apple_order",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
        required_permissions=("orders:write",),
    ),
    _covered(
        "orders.invoice",
        "GET",
        "/orders/{id}/invoice/",
        "Invoices",
        "authenticated",
        "read",
        "Get an order's active invoice.",
        "acedatacloud_get_order_invoice",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=(),
    ),
    _covered(
        "billing_profiles.list",
        "GET",
        "/billing-profiles/",
        "Invoices",
        "authenticated",
        "read",
        "List billing profiles.",
        "acedatacloud_list_billing_profiles",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=(),
    ),
    _covered(
        "invoices.preview",
        "POST",
        "/invoices/preview/",
        "Invoices",
        "authenticated",
        "read",
        "Preview invoice amount.",
        "acedatacloud_preview_invoice",
        "test_billing_tools.py::test_invoice_preview_route",
        required_permissions=(),
    ),
    _covered(
        "invoices.list",
        "GET",
        "/invoices/",
        "Invoices",
        "authenticated",
        "read",
        "List invoices.",
        "acedatacloud_list_invoices",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=(),
    ),
    _covered(
        "invoices.admin_list",
        "GET",
        "/invoices/admin/",
        "Invoices",
        "authenticated",
        "read",
        "List invoices across accounts.",
        "acedatacloud_list_admin_invoices",
        "test_billing_tools.py::test_admin_invoice_status_filter",
        required_permissions=("invoices:read:any",),
    ),
    _covered(
        "invoices.apply",
        "POST",
        "/invoices/",
        "Invoices",
        "authenticated",
        "write",
        "Apply for an invoice.",
        "acedatacloud_apply_invoice",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "invoices.detail",
        "GET",
        "/invoices/{id}/",
        "Invoices",
        "authenticated",
        "read",
        "Get one invoice.",
        "acedatacloud_get_invoice",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=(),
    ),
    _covered(
        "invoices.cancel",
        "POST",
        "/invoices/{id}/cancel/",
        "Invoices",
        "authenticated",
        "consequential",
        "Cancel an invoice.",
        "acedatacloud_cancel_invoice",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "invoices.download",
        "GET",
        "/invoices/{id}/download/",
        "Invoices",
        "authenticated",
        "read",
        "Get a signed invoice URL.",
        "acedatacloud_get_invoice_download",
        "test_billing_tools.py::test_invoice_download_json_url",
        secret_policy="disclose /url only",
        required_permissions=(),
    ),
    _covered(
        "auto_recharge.list",
        "GET",
        "/auto-recharge-configs/",
        "Auto Recharge",
        "authenticated",
        "read",
        "List auto-recharge configs.",
        "acedatacloud_list_auto_recharges",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=("auto-recharge:read",),
    ),
    _covered(
        "auto_recharge.create",
        "POST",
        "/auto-recharge-configs/",
        "Auto Recharge",
        "authenticated",
        "write",
        "Create auto recharge.",
        "acedatacloud_create_auto_recharge",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
        required_permissions=("auto-recharge:write",),
    ),
    _covered(
        "auto_recharge.detail",
        "GET",
        "/auto-recharge-configs/{id}",
        "Auto Recharge",
        "authenticated",
        "read",
        "Get auto recharge.",
        "acedatacloud_get_auto_recharge",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=("auto-recharge:read",),
    ),
    _covered(
        "auto_recharge.update",
        "PATCH",
        "/auto-recharge-configs/{id}",
        "Auto Recharge",
        "authenticated",
        "write",
        "Update auto recharge.",
        "acedatacloud_update_auto_recharge",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
        required_permissions=("auto-recharge:write",),
    ),
    _covered(
        "auto_recharge.delete",
        "DELETE",
        "/auto-recharge-configs/{id}",
        "Auto Recharge",
        "authenticated",
        "consequential",
        "Delete auto recharge.",
        "acedatacloud_delete_auto_recharge",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
        required_permissions=("auto-recharge:write",),
    ),
    _covered(
        "auto_recharge.quote",
        "POST",
        "/auto-recharge-configs/quote/",
        "Auto Recharge",
        "authenticated",
        "read",
        "Quote auto recharge.",
        "acedatacloud_quote_auto_recharge",
        "test_billing_tools.py::test_auto_recharge_quote_route",
        required_permissions=("auto-recharge:read",),
    ),
    _covered(
        "auto_recharge.setup",
        "POST",
        "/auto-recharge-configs/{id}/setup/",
        "Auto Recharge",
        "authenticated",
        "consequential",
        "Create card setup state.",
        "acedatacloud_setup_auto_recharge",
        "test_billing_tools.py::test_setup_exact_secret_disclosure",
        confirm=True,
        secret_policy="disclose /client_secret and /id once",
        required_permissions=("auto-recharge:write",),
    ),
    _covered(
        "auto_recharge.confirm",
        "POST",
        "/auto-recharge-configs/{id}/confirm-setup/",
        "Auto Recharge",
        "authenticated",
        "consequential",
        "Confirm saved card setup.",
        "acedatacloud_confirm_auto_recharge_setup",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
        required_permissions=("auto-recharge:write",),
    ),
    _covered(
        "auto_recharge.disable",
        "POST",
        "/auto-recharge-configs/{id}/disable/",
        "Auto Recharge",
        "authenticated",
        "consequential",
        "Disable auto recharge.",
        "acedatacloud_disable_auto_recharge",
        "test_billing_tools.py::test_billing_mutation_previews_zero_calls",
        confirm=True,
        required_permissions=("auto-recharge:write",),
    ),
    _covered(
        "usage.api.detail",
        "GET",
        "/usage/apis/{id}",
        "Usage",
        "authenticated",
        "read",
        "Get API usage detail.",
        "acedatacloud_get_usage",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=("usage:read",),
    ),
    _covered(
        "usage.api.status_codes",
        "GET",
        "/usage/apis/status-codes/",
        "Usage",
        "authenticated",
        "read",
        "List usage status codes.",
        "acedatacloud_list_usage_status_codes",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=("usage:read",),
    ),
    _covered(
        "usage.api.export",
        "GET",
        "/usage/apis/export/",
        "Usage",
        "authenticated",
        "read",
        "Export bounded usage CSV.",
        "acedatacloud_export_usage",
        "test_billing_tools.py::test_bounded_exports",
        required_permissions=("usage:read",),
    ),
    _covered(
        "usage.proxy.list",
        "GET",
        "/usage/proxies/",
        "Usage",
        "authenticated",
        "read",
        "List proxy usage.",
        "acedatacloud_list_proxy_usage",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=("usage:read",),
    ),
    _covered(
        "usage.proxy.detail",
        "GET",
        "/usage/proxies/{id}",
        "Usage",
        "authenticated",
        "read",
        "Get proxy usage detail.",
        "acedatacloud_get_proxy_usage",
        "test_billing_tools.py::test_billing_read_routes",
        required_permissions=("usage:read",),
    ),
    _covered(
        "distribution.initialize",
        "POST",
        "/distribution-statuses/initialize/",
        "Distribution",
        "authenticated",
        "write",
        "Distribution Initialize",
        "acedatacloud_initialize_distribution",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "distribution.levels",
        "GET",
        "/distribution-levels/",
        "Distribution",
        "authenticated",
        "read",
        "Distribution Levels",
        "acedatacloud_list_distribution_levels",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "distribution.rank",
        "GET",
        "/distribution-histories/rank/",
        "Distribution",
        "authenticated",
        "read",
        "Distribution Rank",
        "acedatacloud_get_distribution_rank",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "distribution.platform_rank",
        "GET",
        "/distribution-histories/platform-rank/",
        "Distribution",
        "authenticated",
        "read",
        "Distribution Platform_Rank",
        "acedatacloud_get_platform_distribution_rank",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "distribution.trend",
        "GET",
        "/distribution-histories/trend/",
        "Distribution",
        "authenticated",
        "read",
        "Distribution Trend",
        "acedatacloud_get_distribution_trend",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "coin.info",
        "GET",
        "/coin-infos/",
        "Coin",
        "authenticated",
        "read",
        "Coin Info",
        "acedatacloud_list_coin_info",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "coin.refresh",
        "POST",
        "/coin-infos/{id}/update-balance/",
        "Coin",
        "authenticated",
        "write",
        "Coin Refresh",
        "acedatacloud_refresh_coin_info",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "coin.wallet.summary",
        "GET",
        "/coin-wallet/summary/",
        "Coin",
        "authenticated",
        "read",
        "Coin Wallet Summary",
        "acedatacloud_get_wallet_summary",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "coin.wallet.challenge",
        "POST",
        "/coin-wallet/challenge/",
        "Coin",
        "authenticated",
        "write",
        "Coin Wallet Challenge",
        "acedatacloud_create_wallet_challenge",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "coin.wallet.confirm",
        "POST",
        "/coin-wallet/confirm/",
        "Coin",
        "authenticated",
        "consequential",
        "Coin Wallet Confirm",
        "acedatacloud_confirm_wallet_challenge",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "access.list",
        "GET",
        "/access-requests/",
        "Access Requests",
        "authenticated",
        "read",
        "Access List",
        "acedatacloud_list_access_requests",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "access.create",
        "POST",
        "/access-requests/",
        "Access Requests",
        "authenticated",
        "write",
        "Access Create",
        "acedatacloud_create_access_request",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "access.detail",
        "GET",
        "/access-requests/{id}",
        "Access Requests",
        "authenticated",
        "read",
        "Access Detail",
        "acedatacloud_get_access_request",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "access.cancel",
        "DELETE",
        "/access-requests/{id}",
        "Access Requests",
        "authenticated",
        "consequential",
        "Access Cancel",
        "acedatacloud_cancel_access_request",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "surveys.list",
        "GET",
        "/surveys/templates/",
        "Surveys",
        "authenticated",
        "read",
        "Surveys List",
        "acedatacloud_list_surveys",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "surveys.detail",
        "GET",
        "/surveys/templates/{alias}/",
        "Surveys",
        "authenticated",
        "read",
        "Surveys Detail",
        "acedatacloud_get_survey",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "surveys.response",
        "GET",
        "/surveys/responses/me/",
        "Surveys",
        "authenticated",
        "read",
        "Surveys Response",
        "acedatacloud_get_survey_response",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "surveys.submit",
        "POST",
        "/surveys/responses/",
        "Surveys",
        "authenticated",
        "write",
        "Surveys Submit",
        "acedatacloud_submit_survey",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "translations.capabilities",
        "GET",
        "/translations/capabilities/",
        "Translation",
        "authenticated",
        "read",
        "Translations Capabilities",
        "acedatacloud_get_translation_capabilities",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "translations.enable",
        "POST",
        "/translations/enable",
        "Translation",
        "authenticated",
        "write",
        "Translations Enable",
        "acedatacloud_enable_translation",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "translations.disable",
        "POST",
        "/translations/disable",
        "Translation",
        "authenticated",
        "write",
        "Translations Disable",
        "acedatacloud_disable_translation",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "preferences.list",
        "GET",
        "/email-marketing/preferences/",
        "Preferences",
        "authenticated",
        "read",
        "Preferences List",
        "acedatacloud_list_email_preferences",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "preferences.update",
        "PUT",
        "/email-marketing/preferences/{topic}/",
        "Preferences",
        "authenticated",
        "write",
        "Preferences Update",
        "acedatacloud_update_email_preference",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "reports.create",
        "POST",
        "/content-reports/",
        "Reports",
        "authenticated",
        "write",
        "Reports Create",
        "acedatacloud_report_content",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "x402.current",
        "GET",
        "/x402/payment-authorization/",
        "X402",
        "authenticated",
        "read",
        "X402 Current",
        "acedatacloud_get_x402_authorization",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=False,
        required_permissions=(),
    ),
    _covered(
        "x402.setup",
        "POST",
        "/x402/payment-authorization/setup/",
        "X402",
        "authenticated",
        "write",
        "X402 Setup",
        "acedatacloud_setup_x402_authorization",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "x402.confirm",
        "POST",
        "/x402/payment-authorization/confirm/",
        "X402",
        "authenticated",
        "consequential",
        "X402 Confirm",
        "acedatacloud_confirm_x402_authorization",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "x402.disable",
        "POST",
        "/x402/payment-authorization/disable/",
        "X402",
        "authenticated",
        "consequential",
        "X402 Disable",
        "acedatacloud_disable_x402_authorization",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "x402.enable",
        "POST",
        "/x402/payment-authorization/enable/",
        "X402",
        "authenticated",
        "consequential",
        "X402 Enable",
        "acedatacloud_enable_x402_authorization",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "x402.revoke",
        "POST",
        "/x402/payment-authorization/revoke-confirm/",
        "X402",
        "authenticated",
        "consequential",
        "X402 Revoke",
        "acedatacloud_confirm_x402_revocation",
        "test_remaining_tools.py::test_remaining_contracts",
        confirm=True,
        required_permissions=(),
    ),
    _covered(
        "sites.initialize",
        "POST",
        "/sites/initialize/",
        "Sites",
        "authenticated",
        "write",
        "Sites Initialize",
        "acedatacloud_initialize_site",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "sites.initialize" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "sites.list",
        "GET",
        "/sites/",
        "Sites",
        "authenticated",
        "read",
        "Sites List",
        "acedatacloud_list_sites",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "sites.list" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "sites.detail",
        "GET",
        "/sites/{id}",
        "Sites",
        "authenticated",
        "read",
        "Sites Detail",
        "acedatacloud_get_site",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "sites.detail" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "sites.update",
        "PATCH",
        "/sites/{id}",
        "Sites",
        "authenticated",
        "write",
        "Sites Update",
        "acedatacloud_update_site",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "sites.update" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "sites.menu_translation",
        "POST",
        "/sites/{id}/menu-translations",
        "Sites",
        "authenticated",
        "write",
        "Sites Menu Translation",
        "acedatacloud_set_site_menu_translation",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "sites.menu_translation" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_domains.list",
        "GET",
        "/site-domains/",
        "Sites",
        "authenticated",
        "read",
        "Site Domains List",
        "acedatacloud_list_site_domains",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_domains.list" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_domains.detail",
        "GET",
        "/site-domains/{id}/",
        "Sites",
        "authenticated",
        "read",
        "Site Domains Detail",
        "acedatacloud_get_site_domain",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_domains.detail" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_domains.create",
        "POST",
        "/site-domains/",
        "Sites",
        "authenticated",
        "write",
        "Site Domains Create",
        "acedatacloud_create_site_domain",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_domains.create" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_domains.update",
        "PATCH",
        "/site-domains/{id}/",
        "Sites",
        "authenticated",
        "write",
        "Site Domains Update",
        "acedatacloud_update_site_domain",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_domains.update" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_domains.delete",
        "DELETE",
        "/site-domains/{id}/",
        "Sites",
        "authenticated",
        "consequential",
        "Site Domains Delete",
        "acedatacloud_delete_site_domain",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_domains.delete" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_domains.verify",
        "POST",
        "/site-domains/{id}/verify/",
        "Sites",
        "authenticated",
        "write",
        "Site Domains Verify",
        "acedatacloud_verify_site_domain",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_domains.verify" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_domains.check",
        "GET",
        "/site-domains/check",
        "Sites",
        "authenticated",
        "read",
        "Site Domains Check",
        "acedatacloud_check_site_domain",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_domains.check" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_domains.frame",
        "GET",
        "/site-domains/frame-ancestors",
        "Sites",
        "authenticated",
        "read",
        "Site Domains Frame",
        "acedatacloud_check_frame_ancestor",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_domains.frame" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_banners.list",
        "GET",
        "/site-banners/",
        "Sites",
        "authenticated",
        "read",
        "Site Banners List",
        "acedatacloud_list_site_banners",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_banners.list" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_banners.public",
        "GET",
        "/site-banners/public/",
        "Sites",
        "authenticated",
        "read",
        "Site Banners Public",
        "acedatacloud_list_site_banners",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_banners.public" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_banners.detail",
        "GET",
        "/site-banners/{id}/",
        "Sites",
        "authenticated",
        "read",
        "Site Banners Detail",
        "acedatacloud_get_site_banner",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_banners.detail" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_banners.create",
        "POST",
        "/site-banners/",
        "Sites",
        "authenticated",
        "write",
        "Site Banners Create",
        "acedatacloud_create_site_banner",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_banners.create" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_banners.update",
        "PATCH",
        "/site-banners/{id}/",
        "Sites",
        "authenticated",
        "write",
        "Site Banners Update",
        "acedatacloud_update_site_banner",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_banners.update" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_banners.delete",
        "DELETE",
        "/site-banners/{id}/",
        "Sites",
        "authenticated",
        "consequential",
        "Site Banners Delete",
        "acedatacloud_delete_site_banner",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_banners.delete" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_capability.list",
        "GET",
        "/site-capability-overrides/",
        "Sites",
        "authenticated",
        "read",
        "Site Capability List",
        "acedatacloud_list_site_capability_overrides",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_capability.list" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_capability.detail",
        "GET",
        "/site-capability-overrides/{id}/",
        "Sites",
        "authenticated",
        "read",
        "Site Capability Detail",
        "acedatacloud_get_site_capability_override",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_capability.detail" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_capability.create",
        "POST",
        "/site-capability-overrides/",
        "Sites",
        "authenticated",
        "write",
        "Site Capability Create",
        "acedatacloud_create_site_capability_override",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_capability.create" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_capability.update",
        "PATCH",
        "/site-capability-overrides/{id}/",
        "Sites",
        "authenticated",
        "write",
        "Site Capability Update",
        "acedatacloud_update_site_capability_override",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_capability.update" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_capability.delete",
        "DELETE",
        "/site-capability-overrides/{id}/",
        "Sites",
        "authenticated",
        "consequential",
        "Site Capability Delete",
        "acedatacloud_delete_site_capability_override",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_capability.delete" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_service.list",
        "GET",
        "/site-service-overrides/",
        "Sites",
        "authenticated",
        "read",
        "Site Service List",
        "acedatacloud_list_site_service_overrides",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_service.list" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_service.detail",
        "GET",
        "/site-service-overrides/{id}/",
        "Sites",
        "authenticated",
        "read",
        "Site Service Detail",
        "acedatacloud_get_site_service_override",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_service.detail" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_service.create",
        "POST",
        "/site-service-overrides/",
        "Sites",
        "authenticated",
        "write",
        "Site Service Create",
        "acedatacloud_create_site_service_override",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_service.create" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_service.update",
        "PATCH",
        "/site-service-overrides/{id}/",
        "Sites",
        "authenticated",
        "write",
        "Site Service Update",
        "acedatacloud_update_site_service_override",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_service.update" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_service.delete",
        "DELETE",
        "/site-service-overrides/{id}/",
        "Sites",
        "authenticated",
        "consequential",
        "Site Service Delete",
        "acedatacloud_delete_site_service_override",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_service.delete" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_document.list",
        "GET",
        "/site-document-overrides/",
        "Sites",
        "authenticated",
        "read",
        "Site Document List",
        "acedatacloud_list_site_document_overrides",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_document.list" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_document.detail",
        "GET",
        "/site-document-overrides/{id}/",
        "Sites",
        "authenticated",
        "read",
        "Site Document Detail",
        "acedatacloud_get_site_document_override",
        "test_sites.py::test_site_contracts",
        confirm=False,
        coverage="shared" if "site_document.detail" == "site_banners.public" else "covered",
        required_permissions=("sites:read",),
    ),
    _covered(
        "site_document.create",
        "POST",
        "/site-document-overrides/",
        "Sites",
        "authenticated",
        "write",
        "Site Document Create",
        "acedatacloud_create_site_document_override",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_document.create" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_document.update",
        "PATCH",
        "/site-document-overrides/{id}/",
        "Sites",
        "authenticated",
        "write",
        "Site Document Update",
        "acedatacloud_update_site_document_override",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_document.update" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _covered(
        "site_document.delete",
        "DELETE",
        "/site-document-overrides/{id}/",
        "Sites",
        "authenticated",
        "consequential",
        "Site Document Delete",
        "acedatacloud_delete_site_document_override",
        "test_sites.py::test_site_contracts",
        confirm=True,
        coverage="shared" if "site_document.delete" == "site_banners.public" else "covered",
        required_permissions=("sites:write",),
    ),
    _excluded(
        "applications.appliance_proxy",
        "ANY",
        "/applications/{id}/appliance-request",
        "Applications",
        "Generic appliance reverse proxy would bypass typed MCP safety boundaries.",
    ),
    _excluded(
        "payments.provider",
        "ANY",
        "/payment/*",
        "Payments",
        "Provider-internal payment APIs are not account control-plane operations.",
    ),
    _excluded(
        "callbacks.oauth",
        "ANY",
        "*/oauth/callback",
        "Protocols",
        "OAuth callbacks are interactive protocol endpoints, not callable tools.",
    ),
    _excluded(
        "callbacks.webhooks",
        "ANY",
        "*/webhook/*",
        "Protocols",
        "Inbound provider callbacks must never be exposed as caller-driven tools.",
    ),
    _excluded(
        "auth.interactive",
        "ANY",
        "/auth/login|register|codes|reset",
        "Protocols",
        "Interactive login, registration, verification codes and password reset remain client flows.",
    ),
    _excluded(
        "webauthn.protocol",
        "ANY",
        "/passkeys/*/challenge|verify",
        "Protocols",
        "WebAuthn challenge and verification require browser-native origin-bound credentials.",
    ),
    _excluded(
        "uploads.public_token",
        "ANY",
        "/uploads/public/*",
        "Protocols",
        "Public tokenized upload callbacks are protocol surfaces, not management tools.",
    ),
)


# Generated business tools and the complete backend route ledger share one source.
from contracts.management_surface import SURFACE_TOOLS  # noqa: E402

OPERATIONS += tuple(
    Operation(
        spec["operation_id"],
        spec["method"],
        spec["path"],
        spec["domain"],
        "covered",
        spec["authentication"],
        tuple(spec["required_permissions"]),
        "write" if spec["confirm"] else "read",
        spec["confirm"],
        "mask",
        "test_management_tools.py::test_confirmed_fixed_routes",
        spec["description"],
        spec["name"],
    )
    for spec in SURFACE_TOOLS
)
