version: "3"
services:
  mcp-gemini:
    platform: linux/amd64
    container_name: "mcp-gemini"
    build: ./
    image: "ghcr.io/acedatacloud/mcp-gemini:${BUILD_NUMBER}"
    ports:
      - "8000:8000"
