version: "3"
services:
  mcp-seedream-pro:
    platform: linux/amd64
    container_name: "mcp-seedream-pro"
    build: ./
    image: "ghcr.io/acedatacloud/mcp-seedream-pro:${BUILD_NUMBER}"
    ports:
      - "8000:8000"
