"""Apply shared UTM conventions to every active MCP's public README links.

README.md remains the editable GitHub source. README.pypi.md is generated from
it with a distinct channel. Existing marketplace READMEs are normalized in place.
Protocol URLs, code examples, retired packages and non-platform URLs are untouched.
"""

import argparse
import hashlib
import json
import re
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

try:
    from .mcp_catalog import documentation_target, load_catalog
except ImportError:
    from mcp_catalog import documentation_target, load_catalog

ROOT = Path(__file__).resolve().parents[1]
GENERATED = (
    "<!-- Generated by scripts/marketing_readmes.py from README.md; do not edit. -->\n"
)
LINK = re.compile(r"(?<!!)\[([^\]\n]+)\]\((https://platform\.acedata\.cloud[^\s)]*)\)")


def contract():
    data = json.loads((ROOT / "contracts/marketing-attribution.json").read_text())
    canonical = json.dumps(
        data["contract"], sort_keys=True, separators=(",", ":")
    ).encode()
    if (
        data.get("profile") != "links"
        or hashlib.sha256(canonical).hexdigest() != data["sha256"]
    ):
        raise ValueError("Invalid marketing links projection")
    return data["contract"]


def tagged_url(url, alias, source, rules, catalog):
    parts = urlsplit(url)
    if parts.scheme != "https" or parts.netloc != "platform.acedata.cloud":
        return url
    if parts.path.startswith("/api/"):
        return url
    canonical, _ = documentation_target(catalog[alias])
    destination = urlunsplit((parts.scheme, parts.netloc, parts.path, "", ""))
    if destination == canonical:
        placement = "quick_start"
    elif parts.path.startswith("/console/platform-tokens"):
        placement = "platform_token"
    elif parts.path.startswith("/console/applications"):
        placement = "api_key"
    elif parts.path in ("", "/"):
        placement = "platform"
    else:
        placement = re.sub(r"[^a-z0-9_.-]", "_", parts.path.strip("/").lower())
    surface = rules["link_defaults"]["surfaces"][source]
    content = rules["link_defaults"]["content_template"].format(
        entry=alias.replace("-", "_") + "_mcp", surface=surface, placement=placement
    )
    limit = rules["max_tag_length"]
    if len(content) > limit:
        content = (
            content[: limit - 9]
            + "_"
            + hashlib.sha256(content.encode()).hexdigest()[:8]
        )
    tags = {
        "utm_source": source,
        "utm_medium": rules["sources"][source],
        "utm_campaign": rules["link_defaults"]["campaign"],
        "utm_content": content,
    }
    if any(not re.fullmatch(rules["tag_pattern"], value) for value in tags.values()):
        raise ValueError("Invalid generated marketing tag")
    query = [
        (key, value)
        for key, value in parse_qsl(parts.query, keep_blank_values=True)
        if key not in rules["utm_keys"]
    ]
    query.extend(tags.items())
    return urlunsplit(
        (parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment)
    )


def render(text, alias, source, rules=None, catalog=None):
    rules = rules or contract()
    catalog = catalog or load_catalog()
    if catalog[alias]["status"] != "active":
        return text
    output = []
    fence = None
    for line in text.splitlines(keepends=True):
        marker = re.match(r"\s*(`{3,}|~{3,})", line)
        if marker:
            if fence is None:
                fence = marker[1][0]
            elif marker[1][0] == fence:
                fence = None
            output.append(line)
            continue
        if fence:
            output.append(line)
            continue
        # Inline code, including URLs in configuration examples, stays byte-identical.
        chunks = re.split(r"(`+[^`]*`+)", line)
        for i in range(0, len(chunks), 2):
            chunks[i] = LINK.sub(
                lambda m: f"[{m[1]}]({tagged_url(m[2], alias, source, rules, catalog)})",
                chunks[i],
            )
            # Bare resource links at the end of a prose line are also clickable.
            chunks[i] = re.sub(
                r"(?<![\w/(\[?=])https://platform\.acedata\.cloud[^\s)>]*?(?=\s*$)",
                lambda m: tagged_url(m[0], alias, source, rules, catalog),
                chunks[i],
            )
        output.append("".join(chunks))
    return "".join(output)


def outputs():
    rules, catalog = contract(), load_catalog()
    for alias, entry in catalog.items():
        if entry["status"] != "active":
            continue
        path = ROOT / alias / "README.md"
        source = path.read_text()
        source = re.sub(
            r"^<!-- Generated by scripts/seedance_readmes.py[^\n]*\n", "", source
        )
        yield path, render(source, alias, "github", rules, catalog)
        yield (
            path.with_name("README.pypi.md"),
            GENERATED + render(source, alias, "pypi", rules, catalog),
        )
        project_path = ROOT / alias / "pyproject.toml"
        project = project_path.read_text()
        destination, _ = documentation_target(entry)
        project = re.sub(
            r'^Documentation = ".*"$',
            'Documentation = "'
            + tagged_url(destination, alias, "pypi", rules, catalog)
            + '"',
            project,
            flags=re.MULTILINE,
        )
        yield project_path, project
        for directory, channel in (
            ("vscode", "vscode_marketplace"),
            ("jetbrains", "jetbrains_marketplace"),
        ):
            path = ROOT / alias / directory / "README.md"
            if path.exists():
                yield path, render(path.read_text(), alias, channel, rules, catalog)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in outputs():
        if path.exists() and path.read_text() == expected:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.write_text(expected)
    if args.check and stale:
        raise SystemExit("Stale marketing READMEs: " + ", ".join(stale))
    print(f"Marketing READMEs: {len(stale)} {'stale' if args.check else 'updated'}")


if __name__ == "__main__":
    main()
