"""Generate GitHub/PyPI documentation from the pinned attribution contract."""

import argparse
import hashlib
import json
from pathlib import Path
from urllib.parse import urlencode

ROOT = Path(__file__).resolve().parents[1]


def render(source):
    snapshot = json.loads((ROOT / "contracts/marketing-attribution.json").read_text())
    contract = snapshot["contract"]
    canonical = json.dumps(contract, sort_keys=True, separators=(",", ":")).encode()
    if hashlib.sha256(canonical).hexdigest() != snapshot["sha256"]:
        raise ValueError("Marketing contract hash mismatch")
    surface = "readme" if source == "github" else "package"
    result = (ROOT / "seedance/README.template.md").read_text()
    for name, placement in [("setup_url", "quick_start"), ("api_key_url", "api_key")]:
        content = f"seedance_mcp_{surface}_{placement}"
        item = contract["contents"][content]
        if source not in item["sources"]:
            raise ValueError("Source not allowed for content")
        tags = {"utm_source": source, "utm_medium": contract["sources"][source], "utm_campaign": "evergreen", "utm_content": content}
        result = result.replace("{{" + name + "}}", item["destination"] + "?" + urlencode(tags))
    return "<!-- Generated by scripts/seedance_readmes.py; edit README.template.md. -->\n" + result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for source, name in [("github", "README.md"), ("pypi", "README.pypi.md")]:
        path = ROOT / "seedance" / name
        expected = render(source)
        if args.check:
            if not path.exists() or path.read_text() != expected:
                raise SystemExit(f"Stale generated README: {path.relative_to(ROOT)}")
        else:
            path.write_text(expected)


if __name__ == "__main__":
    main()
