version: "3"
services:
  mcp-digitalhuman:
    platform: linux/amd64
    container_name: "mcp-digitalhuman"
    build: ./
    image: "ghcr.io/acedatacloud/mcp-digitalhuman:${BUILD_NUMBER}"
    ports:
      - "8000:8000"
