version: "3"
services:
  mcp-deepseek:
    platform: linux/amd64
    container_name: "mcp-deepseek"
    build: ./
    image: "ghcr.io/acedatacloud/mcp-deepseek:${BUILD_NUMBER}"
    ports:
      - "8000:8000"
